export { default as checkFizzBuzz } from './checkFizzBuzz'
export { default as checkFizz } from './checkFizz'
export { default as checkBuzz } from './checkBuzz'
export { default as passNumber } from './passNumber'
export { fetchData } from './getDataFromAPI'
