export { default as checkFizzBuzz } from './checkFizzBuzz'
export { default as checkFizz } from './checkFizz'
export { default as checkBuzz } from './checkBuzz'
export { default as passNumber } from './passNumber'
export { requestIsLoading, requestHasErrored, requestFetchDataSuccess } from './setFetchStatus'
export { default as getData } from './getData'
